/*
 *  Copyright IBM Corp. 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

import "@carbon/ai-chat/dist/es/web-components/cds-aichat-custom-element/index.js";

import {
  BusEventType,
  CarbonTheme,
  PanelType,
  type ChatInstance,
  type MessageResponse,
  type PublicConfig,
  type UserDefinedItem,
} from "@carbon/ai-chat";
import { css, html, LitElement } from "lit";
import { customElement, state } from "lit/decorators.js";

import { customSendMessage } from "./customSendMessage";
import "./inventory-report-example";
import "./inventory-status-example";
import "./outstanding-orders-example";
import "./outstanding-orders-card";

interface UserDefinedSlotsMap {
  [key: string]: UserDefinedSlot;
}

interface UserDefinedSlot {
  message: UserDefinedItem;
  fullMessage: MessageResponse;
}

const config: PublicConfig = {
  messaging: {
    customSendMessage,
  },
  layout: {
    showFrame: false,
    customProperties: {
      "messages-max-width": `max(60vw, 672px)`,
    },
  },
  openChatByDefault: true,
  injectCarbonTheme: CarbonTheme.WHITE,
};

@customElement("my-app")
export class Demo extends LitElement {
  static styles = css`
    .chat-custom-element {
      height: 100vh;
      width: 100vw;
    }
  `;

  @state()
  accessor instance!: ChatInstance;

  @state()
  accessor activeResponseId: string | null = null;

  @state()
  accessor workspaceType: string | null = null;

  @state()
  accessor workspaceId: string | undefined = undefined;

  @state()
  accessor workspaceAdditionalData: any = null;

  @state()
  accessor userDefinedSlotsMap: UserDefinedSlotsMap = {};

  onBeforeRender = (instance: ChatInstance) => {
    // Set the instance in state.
    this.instance = instance;
    const initialState = instance.getState();
    this.activeResponseId = initialState.activeResponseId ?? null;

    instance.on({
      type: BusEventType.STATE_CHANGE,
      handler: (event: any) => {
        if (
          event.previousState?.activeResponseId !==
          event.newState?.activeResponseId
        ) {
          this.activeResponseId = event.newState.activeResponseId ?? null;
        }
      },
    });

    // Register user defined response handler.
    instance.on({
      type: BusEventType.USER_DEFINED_RESPONSE,
      handler: this.userDefinedHandler,
    });

    // Register workspace panel handlers.
    instance.on({
      type: BusEventType.WORKSPACE_PRE_OPEN,
      handler: this.workspacePanelPreOpenHandler,
    });

    instance.on({
      type: BusEventType.WORKSPACE_OPEN,
      handler: this.workspacePanelOpenHandler,
    });

    instance.on({
      type: BusEventType.WORKSPACE_CLOSE,
      handler: this.workspacePanelCloseHandler,
    });
  };

  /**
   * Handles when the workspace panel is about to open.
   */
  workspacePanelPreOpenHandler = (event: any) => {
    console.log(event, "Workspace panel pre-open");
  };

  /**
   * Handles when the workspace panel is opened.
   */
  workspacePanelOpenHandler = (event: any) => {
    console.log(event, "Workspace panel opened");

    // Extract workspace data from the event
    const { workspaceId, additionalData } = event.data;
    this.workspaceId = workspaceId;
    this.workspaceAdditionalData = additionalData;
    this.workspaceType = (additionalData as { type?: string })?.type || null;
  };

  /**
   * Handles when the workspace panel is closed.
   */
  workspacePanelCloseHandler = (event: any) => {
    console.log(event, "Workspace panel closed");

    // Clear workspace data when panel closes
    this.workspaceType = null;
    this.workspaceId = undefined;
    this.workspaceAdditionalData = null;
  };

  /**
   * Each user defined event is tied to a slot deeply rendered within AI chat that is generated at runtime.
   * Here we make sure we store all these slots along with their relevant data in order to be able to dynamically
   * render the content to be slotted when this.renderUserDefinedSlots() is called in the render function.
   */
  userDefinedHandler = (event: any) => {
    const { data } = event;
    this.userDefinedSlotsMap[data.slot] = {
      message: data.message,
      fullMessage: data.fullMessage,
    };
    this.requestUpdate();
  };

  /**
   * This renders each of the dynamically generated slots that were generated by the AI chat by calling
   * this.renderUserDefinedResponse on each one.
   */
  renderUserDefinedSlots() {
    const userDefinedSlotsKeyArray = Object.keys(this.userDefinedSlotsMap);
    return userDefinedSlotsKeyArray.map((slot) => {
      return this.renderUserDefinedResponse(slot);
    });
  }

  /**
   * Here we process a single item from this.userDefinedSlotsMap. We go ahead and use a switch statement to decide
   * which element we should be rendering.
   */
  renderUserDefinedResponse(slot: keyof UserDefinedSlotsMap) {
    const slotData = this.userDefinedSlotsMap[slot];
    if (!slotData) {
      return null;
    }

    const { message } = slotData;
    const userDefinedMessage = message;

    // Check the "type" we have used as our key.
    switch (userDefinedMessage.user_defined?.user_defined_type) {
      case "outstanding_orders_card":
        return html`<div slot=${slot}>
          <outstanding-orders-card
            .workspaceId=${userDefinedMessage.user_defined?.workspace_id}
            .additionalData=${userDefinedMessage.user_defined?.additional_data}
            .onMaximize=${() => {
              // Open workspace using the panels API
              const workspaceId = userDefinedMessage.user_defined
                ?.workspace_id as string;
              const additionalData = userDefinedMessage.user_defined
                ?.additional_data as { type?: string };
              this.workspaceId = workspaceId;
              this.workspaceAdditionalData = additionalData;
              this.workspaceType = additionalData?.type || null;

              // Use the customPanels API to open the workspace
              const panel = this.instance.customPanels?.getPanel(
                PanelType.WORKSPACE,
              );
              if (panel) {
                panel.open({
                  workspaceId,
                  additionalData,
                });
              }
            }}
          ></outstanding-orders-card>
        </div>`;
      default:
        return null;
    }
  }

  /**
   * Renders the workspace panel element when the workspace slot is set.
   */
  renderWorkspaceElement() {
    if (!this.workspaceType) {
      return html``;
    }

    switch (this.workspaceType) {
      case "inventory_report":
        return html`<inventory-report-example
          .instance=${this.instance}
          .workspaceId=${this.workspaceId}
          .additionalData=${this.workspaceAdditionalData}
          location="workspace"
          valueFromParent="Hello from parent!"
        ></inventory-report-example>`;
      case "inventory_status":
        return html`<inventory-status-example
          .instance=${this.instance}
          .workspaceId=${this.workspaceId}
          .additionalData=${this.workspaceAdditionalData}
          location="workspace"
        ></inventory-status-example>`;
      case "outstanding_orders":
        return html`<outstanding-orders-example
          .instance=${this.instance}
          .workspaceId=${this.workspaceId}
          .additionalData=${this.workspaceAdditionalData}
          location="workspace"
        ></outstanding-orders-example>`;
      default:
        return html``;
    }
  }

  render() {
    return html`
      <cds-aichat-custom-element
        .onBeforeRender=${this.onBeforeRender}
        .messaging=${config.messaging}
        .layout=${config.layout}
        .openChatByDefault=${config.openChatByDefault}
        .injectCarbonTheme=${config.injectCarbonTheme}
        class="chat-custom-element"
      >
        ${this.renderUserDefinedSlots()}
        <div slot="workspacePanelElement">${this.renderWorkspaceElement()}</div>
      </cds-aichat-custom-element>
    `;
  }
}
